workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 120

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
        - pattern: ana

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods
        - ios/Pods

    scripts:
      - name: Clean Flutter
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: iOS Pod Install FIXED
        script: |
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock .symlinks
          pod install --repo-update
          cd ..

      - name: Build iOS Release
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app