workflows:
  ios-production:
    name: iOS Production Build
    max_build_duration: 120

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
        - pattern: ana
          include: true

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - ios/.symlinks
        - build/

    scripts:
      - name: Clean project
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Reset iOS Pods (FIX FIREBASE)
        script: |
          cd ios
          rm -rf Pods Podfile.lock .symlinks
          pod repo update
          pod install
          cd ..

      - name: Build iOS Release (no codesign)
        script: flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa

    publishing:
      email:
        recipients:
          - mustafasengunms@gmail.com
        notify:
          success: true
          failure: true