name: evren_tarim_market
description: "Evren Ticaret İş Takip Projesi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 1.0.9

  # --- VERİTABANI VE SİSTEM ---
  sqflite: 2.4.2+1
  path: 1.9.1
  sqflite_common_ffi: 2.4.0+3
  synchronized: 3.4.0+1

  # --- FIREBASE (Hata Almayan Sabit Sürümler) ---
  firebase_core: 3.15.2
  cloud_firestore: 5.6.12
  firebase_storage: 12.4.10
  firebase_auth: 5.7.0

  # --- MEDYA VE DOSYA YÖNETİMİ ---
  image_picker: 1.2.2
  path_provider: 2.1.5
  file_picker: 11.0.2
  open_file: 3.5.11
  excel: 4.0.6

  # --- PDF VE PAYLAŞIM ---
  pdf: 3.12.0
  share_plus: 12.0.2
  printing: 5.14.3
  intl: 0.20.2
  syncfusion_flutter_pdf: 33.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo.png
  fonts:
    - family: arial
      fonts:
        - asset: assets/fonts/arial.ttf
        - asset: assets/fonts/arialbd.ttf
          weight: 700