platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Eğer bir şekilde Flutter kancaları yüklenebilirse diye hata almaması için respond_to ekliyoruz
  if respond_to?(:flutter_install_all_ios_pods)
    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Flutter ayarlarını güvenli bir şekilde kontrol ederek çalıştır
    if respond_to?(:flutter_additional_ios_build_settings)
      flutter_additional_ios_build_settings(target)
    end

    target.build_configurations.each do |config|
      # Tüm podlar için iOS 15 ve mimari ayarlarını manuel yapıyoruz
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'
    end
  end
end